name: "Publish Artifacts"
description: Publishes the build artifacts
runs:
  using: composite
  steps:
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: switch-library-manager.windows-amd64
        path: output/windows-amd64/*
        if-no-files-found: error
      
    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: switch-library-manager.linux-amd64
        path: output/linux-amd64/*
        if-no-files-found: error
      
    - name: Upload Mac build
      uses: actions/upload-artifact@v4
      with:
        name: switch-library-manager.darwin-amd64
        path: output/darwin-amd64/*
        if-no-files-found: error